# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6n5oR7wPHhWadzRasoTm-v-2LtXj60U
"""

nome = input('Digite seu nome: ')
print('Prazer em conhece-lo, {}!'.format(nome))